apiVersion: v1
kind: ConfigMap
metadata:
  name: rednote-mcp-cookies
data:
  xiaohongshu-cookies.json: |
    [
      {
        "name": "abRequestId",
        "value": "19967436-5704-5db7-813a-67e0f262df2e",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": true,
        "sameSite": "Lax"
      },
      {
        "name": "webBuild",
        "value": "4.84.2",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": false,
        "sameSite": "Lax"
      },
      {
        "name": "xsecappid",
        "value": "xhs-pc-web",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": 1793693251,
        "httpOnly": false,
        "secure": false,
        "sameSite": "Lax"
      },
      {
        "name": "a1",
        "value": "19a486ba859s6p5bzbg0r6p9ry7ugwywosurqfwvp40000947199",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": true,
        "sameSite": "Lax"
      },
      {
        "name": "webId",
        "value": "bd79a6f97f6cb3d41747c151ecb7786c",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": true,
        "sameSite": "Lax"
      },
      {
        "name": "acw_tc",
        "value": "0a4a476817621516067595702e39e32b313284d49886a3ef194c38eed8c3b9",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": true,
        "sameSite": "Lax"
      },
      {
        "name": "gid",
        "value": "yj04YKDSYjlSyj04YKD0YMiE2jMKU2DuDk8F7hUKUjFvWF487kEvEA888j4Wyjj8D84qD42q",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": 1796717212.501193,
        "httpOnly": false,
        "secure": false,
        "sameSite": "Lax"
      },
      {
        "name": "web_session",
        "value": "040069b70e3f765d56f3a6043d3b4b26e12449",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": true,
        "sameSite": "Lax"
      },
      {
        "name": "unread",
        "value": "{\"ub\":\"6906daa800000000070151fa\",\"ue\":\"690217ee0000000005038f8a\",\"uc\":28}",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": -1,
        "httpOnly": false,
        "secure": true,
        "sameSite": "Lax"
      },
      {
        "name": "websectiga",
        "value": "9730ffafd99f2d09dc024760e253af6ab1feb0002827740b95a255ddf7847fc8",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": 1762416402,
        "httpOnly": false,
        "secure": false,
        "sameSite": "Lax"
      },
      {
        "name": "sec_poison_id",
        "value": "63b944ca-32d5-4b49-adb6-f39d153c8bbe",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": 1762157807,
        "httpOnly": false,
        "secure": false,
        "sameSite": "Lax"
      },
      {
        "name": "loadts",
        "value": "1762157251770",
        "domain": ".xiaohongshu.com",
        "path": "/",
        "expires": 1793693251,
        "httpOnly": false,
        "secure": false,
        "sameSite": "Lax"
      }
    ]